### ISSUE TITLE
Code for Miss: Multi-interest self-supervised learning framework for click-through rate prediction.

### ISSUE THREAD

**Issue by zyx1017** [anonymous98989/anonymous_rec_cigf#1]
你好，最近在读您的这篇文章，有些地方并没有理解的很透彻，想咨询下这篇文章的代码是否已经开源，想借助代码进行学习。谢谢！

**Comment by anonymous98989** [comment]
目前这篇文章还在投，还没有开源，要是出结果中了，到时候在开源哈~谢谢你的关注和认可!



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 12, 2023 15:59 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [MC-CV/CIGF] Code for Miss: Multi-interest self-supervised learningframework for click-through rate prediction. (Issue #1)




 
你好，最近在读您的这篇文章，有些地方并没有理解的很透彻，想咨询下这篇文章的代码是否已经开源，想借助代码进行学习。谢谢！

**Comment by MC-CV** [comment]
> 你好，最近在读您的这篇文章，有些地方并没有理解的很透彻，想咨询下这篇文章的代码是否已经开源，想借助代码进行学习。谢谢！

请您联系guowei67@huawei.com，此code是[Compressed Interaction Graph based Framework for Multi-behavior Recommendation](https://arxiv.org/abs/2303.02418)这篇文章的代码，本人及本repo仅对该文章负责。
