### ISSUE TITLE
实例级建模？

### ISSUE THREAD

**Issue by Kid-Young** [anonymous98989/anonymous_rec_cigf#3]
Hello, What a nice work! But I don't understand what the meaning of instance-level and the beneficial of instance-level model???

**Comment by MC-CV** [comment]
实例级建模本质上就是在GNN的每一层级对异质的信息进行“选择”，相比于行为级的建模，实例级建模在message passing的过程中就充分建模了每个节点（用户/物品）不同类型边（不同行为）的构图路径，其能充分利用异质信息且具有更高的可解释性（具体可见文中table 6的可视化）。而行为级的建模则分别对不同行为进行构图，最后汇聚输出表征。
